### ISSUE TITLE
TypeError when attempting to subset (roi) a DataArray using salem

### ISSUE THREAD

**Issue by Martin-Jung** [fmaussion/salem#102]
I'm trying to use salem for masking out a specific region (defined by a shapefile) in my xarray.
Array and shapefile loaded in correctly and are recognized as such.

Yet when attempting to use "roi" on my DataArray, i get a typeerror. 
`sub = ds.salem.roi(shape=shdf)`

```
Traceback (most recent call last):

  File "<ipython-input-62-53ac7c79df8c>", line 1, in <module>
    sub = ds.salem.roi(shape=shdf)

  File "C:\Anaconda\lib\site-packages\salem\sio.py", line 501, in roi
    mask = self.grid.region_of_interest(**kwargs)

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 1009, in region_of_interest
    inplace=inplace)

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 1229, in transform_geopandas
    result = out.geometry.apply(lambda geom: shapely_transform(project, geom))

  File "C:\Anaconda\lib\site-packages\pandas\core\series.py", line 2551, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)

  File "pandas/_libs/src/inference.pyx", line 1521, in pandas._libs.lib.map_infer

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 1229, in <lambda>
    result = out.geometry.apply(lambda geom: shapely_transform(project, geom))

  File "C:\Anaconda\lib\site-packages\shapely\ops.py", line 246, in transform
    [func(*c) for c in geom.exterior.coords])

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 652, in transform
    x, y = transform_proj(_crs, self.proj, x, y)

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 1157, in transform_proj
    if proj_is_same(p1, p2):

  File "C:\Anaconda\lib\site-packages\salem\gis.py", line 1123, in proj_is_same
    s1.ImportFromProj4(p1.srs)

  File "C:\Anaconda\lib\site-packages\osgeo\osr.py", line 1113, in ImportFromProj4
    return _osr.SpatialReference_ImportFromProj4(self, *args)

TypeError: in method 'SpatialReference_ImportFromProj4', argument 2 of type 'char *'
```
It seems as if salem is expecting some spatial reference or proj4 attribute to be avaialble?

My DataArray (too large to share) looks this:

```
 <xarray.DataArray (year: 34, Latitude: 1318, Longitude: 1555)>
 [69682660 values with dtype=float32]
 Coordinates:
   * year       (year) int64 1984 1985 1986 1987 1988 1989 1990 1991 1992 ...
   * Latitude   (Latitude) float64 32.6 32.6 32.6 32.6 32.6 32.6 32.6 32.6 ...
   * Longitude  (Longitude) float64 -87.94 -87.94 -87.94 -87.94 -87.94 -87.94 ...
 Attributes:
     crs:         +init=epsg:4326
     is_tiled:    0
     nodatavals:  (-3.4e+38, -3.4e+38, -3.4e+38, -3.4e+38, -3.4e+38, -3.4e+38,...
     transform:   (-87.9403950755027, 0.0002694945852365922, 0.0, 32.599951492...
     res:         (0.0002694945852365922, 0.00026949458523998555)
```

* Python ver.  **2.7.14**
* xarray ver. **0.10.3**
* salem ver. **0.2.1**

**Comment by fmaussion** [comment]
Thanks for the report! 


There is a probable conflict with the ``crs`` attribute in your file. Could you try to delete the ``crs`` attribute and try again?

```
del data.attrs['crs']
```

If this still doesn't work, can you try to update Salem first and report back? 

In your conda environment, type:

```
pip install --upgrade git+https://github.com/fmaussion/salem.git
```

**Comment by Martin-Jung** [comment]
Thanks for the quick reply. 

No, both did not work.
* I deleted the attributed, yet without implications
* I also installed the newest github build, but I'm still getting the same error.

I will try it out on python3 on my linux machine later and edit this post accordingly.

Another idea:
Could it be because the underlying file in my case is not as netcdf file and therefore has not all CF-compliant attributes ?
My arrays (Landsat stacks) are stored as geoTiffs and I generally load them via
`ds = xr.open_rasterio(route).rename({'x': 'Longitude', 'y': 'Latitude', 'band': 'year' })                         `

**Comment by fmaussion** [comment]
would you mind sharing a subset of the file here? e.g. ``da.isel(longitude=slice(0, 50), latitude=slice(0, 40)).to_netcdf('subset.nc')``.

I'd be glad to have a look at it

**Comment by Martin-Jung** [comment]
Here is a subset for you. 
In case the NA value is not correctly encoded, values equal to 0 should be set to NA.
CRS is WGS 1984

[test_subset.zip](https://github.com/fmaussion/salem/files/2108039/test_subset.zip)

**Comment by fmaussion** [comment]
It seems to work for me on master: maybe the problem comes from the shapefile? Does your shapefile have all metadata associated to it, including a ``.prj`` file? Could you share it too?
