### ISSUE TITLE
Add topographical shading to map generated by Geogrid simulator

### ISSUE THREAD

**Issue by zxdawn** [fmaussion/salem#135]
I want to use `topographical shading` instead of `natural_earth` when plotting area defind by [namelist.wps](https://github.com/fmaussion/salem/files/2690849/namelist.wps.txt).

Code:
```
from salem.utils import get_demo_file
from salem import geogrid_simulator
import matplotlib.pyplot as plt

fpath='namelist.wps'
g, maps = geogrid_simulator(fpath)
maps[0].set_topography(get_demo_file('hef_srtm.tif'))
maps[0].set_lonlat_contours()
maps[0].visualize(title='Domains 1 to 3')
```

Here's the error:
```
Traceback (most recent call last):
  File "/home/xin/cg/plot.py", line 7, in <module>
    maps[0].set_topography(get_demo_file('hef_srtm.tif'))
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/salem/graphics.py", line 888, in set_topography
    crs=wgs84, margin=10)
  File "/home/xin/Software/anaconda3/lib/python3.6/site-packages/salem/datasets.py", line 181, in set_subset
    raise RuntimeError('subset not valid')
RuntimeError: subset not valid
```

However, this example works fine:
```
from salem import mercator_grid, Map, get_demo_file, open_xr_dataset
grid = mercator_grid(center_ll=(10.76, 46.79), extent=(18000, 14000))
smap = Map(grid, countries=False)
z = smap.set_topography(get_demo_file('hef_srtm.tif'))
smap.set_data(z)
smap.set_cmap('topo')
smap.visualize(title='Topography', cbar_title='m a.s.l.')
```

**Comment by zxdawn** [comment]
I checked the condition in `datasets.py`
https://github.com/fmaussion/salem/blob/2d10174b25bab2786c45d37c752f72a3344bffea/salem/datasets.py#L178-L181

Here's the result:
```
max(sub_x) 148234
max(sub_y) 31341
min(sub_x) 116714 mx 383
min(sub_y) 7316 mx 283
```

It seems something is wrong in transform.

**Comment by fmaussion** [comment]
Thanks!

To use topographical shading in salem, you have to download your own topography data. In this line:

> maps[0].set_topography(get_demo_file('hef_srtm.tif'))

you use the topography file `hef_srtm.tif`, which is a very small subset of the Alps.

**Comment by zxdawn** [comment]
@fmaussion Do you have any suggested file I can download directly?
