### ISSUE TITLE
Transform does not work with (self-built) xr.DataSet

### ISSUE THREAD

**Issue by jlandmann** [fmaussion/salem#147]
Say I have this piece of code:

    sg = salem.Grid(proj='+datum=WGS84 +k=0.9996 +lat_0=0 +lon_0=8.336274703953947 +no_defs +proj=tmerc +units=m +x_0=0 +y_0=0', dxdy=(100, -100), x0y0=(-12991., 5155212.), nxny=(3, 4))
    ds = sg.to_dataset()
    ds = ds.assign_coords(time=np.array([datetime.date(2018, 1, 1), datetime.date(2018, 1, 2)], dtype=object))
    ds['some_variable'] = (['x', 'y', 'time'], np.empty((3, 4, 2)))

If I now want to transform `ds` (for simplicity) onto itself, the following happens, even though there is a `pyproj_srs` attribute:

    ds.salem.transform(ds)
    Traceback (most recent call last):
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
       exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-35-50ce9e33d219>", line 1, in <module>
    ds.salem.transform(ds)
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\salem\sio.py", line 647, in transform
    return self._apply_transform(transform, grid, other)
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\salem\sio.py", line 589, in _apply_transform
    rdata = transform(var)
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\salem\gis.py", line 878, in map_gridded_data
    grid = data.salem.grid  # try xarray
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\xarray\core\extensions.py", line 27, in __get__
    accessor_obj = self._accessor(obj)
    File "C:\Program Files\Anaconda3\envs\*\lib\site-packages\salem\sio.py", line 391, in __init__
    raise RuntimeError('dataset Grid not understood.')
    RuntimeError: dataset Grid not understood.

Funnily, calling `grid_from_dataset` with `ds` directly works completely fine.
If I try to transform before I assign the variable, it "works", but it destroys all coordinates. The output then is:

    <xarray.Dataset>
    Dimensions:  ()
    Data variables:
    *empty*
    Attributes:
    pyproj_srs:  +datum=WGS84 +k=0.9996 +lat_0=0 +lon_0=8.336274703953947 +no...

Transposing such that `'y'` and `'x'` are the last dimensions (as requested [here](https://github.com/fmaussion/salem/blob/08dc357519c7f3bedb04a4f7f520fa0bc5fd6c2e/salem/gis.py#L857)) doesn't help, neither does constructing a fresh dataset from scratch.
It's a bit puzzling to me...what's wrong here?

**Comment by jlandmann** [comment]
Ok, after some time distracted with other things I found one solution: assigning a `pyproj_srs` to the attributes of the variable makes it work:

    ds.some_variable.attrs['pyproj_srs'] = sg.proj.srs
