### ISSUE TITLE
ValueError: crs not understood

### ISSUE THREAD

**Issue by nickbsb** [fmaussion/salem#152]
import numpy as np
import xarray as xr
import salem
da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['lat', 'lon'],
                   coords={'lat':np.linspace(0, 30, 4),
                           'lon':np.linspace(-20, 20, 5)})
da.salem.quick_map()

But the errors show ' ValueError: crs not understood',how to solve this ?

**Comment by fmaussion** [comment]
Can you send:
- full traceback
- salem version
- OS

This works with latest salem for me, works on linux, and works [on the docs](https://salem.readthedocs.io/en/v0.2.3/xarray_acc.html), so it's hard for me to assess what could go wrong...

**Comment by byersiiasa** [comment]
I have the same issue:
```
`Traceback (most recent call last):

  File "<ipython-input-16-42c99e2e2df6>", line 1, in <module>
    da.salem.quick_map()

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 705, in quick_map
    return self._quick_map(self._obj, ax=ax, interp=interp, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 548, in _quick_map
    smap = self.get_map(**kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 537, in get_map
    return Map(self.grid, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\graphics.py", line 426, in __init__
    self.set_shapefile(countries=countries)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\graphics.py", line 678, in set_shapefile
    return self.set_shapefile(shapefiles['world_borders'], **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\graphics.py", line 693, in set_shapefile
    shape = sio.read_shapefile_to_grid(shape, grid=self.grid)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 117, in read_shapefile_to_grid
    **grid.to_dict())

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\joblib\memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\joblib\memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\joblib\memory.py", line 734, in call
    output = self.func(*args, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 87, in _memory_shapefile_to_grid
    e = grid.extent_in_crs(crs=shape.crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 525, in extent_in_crs
    poly = self.extent_as_polygon(crs=crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 553, in extent_as_polygon
    _i, _j = self.corner_grid.ij_to_crs(_i, _j, crs=crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 634, in ij_to_crs
    raise ValueError('crs not understood')

ValueError: crs not understood`
```

Salem 0.2.4
Xarray 0.12.3
Windows 10
Python 3.7, Anaconda build

**Comment by fmaussion** [comment]
Can you try to install from master, and update pyproj as well in the process?

```
pip install git+https://github.com/fmaussion/salem.git
```

**Comment by byersiiasa** [comment]
Just tried with master. Same issue. Same error also when running the 
`da.salem.roi()` command

```
Traceback (most recent call last):

  File "<ipython-input-15-5c6a7b9b7a89>", line 2, in <module>
    hr_crop_wels[sector+'_basin'] = hr_crop_wels[sector].salem.roi(shape=shdf)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\sio.py", line 506, in roi
    mask = self.grid.region_of_interest(**kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 1029, in region_of_interest
    inplace=inplace)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 1310, in transform_geopandas
    result = out.geometry.apply(lambda geom: transform(project, geom))

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\pandas\core\series.py", line 3591, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)

  File "pandas/_libs/lib.pyx", line 2217, in pandas._libs.lib.map_infer

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 1310, in <lambda>
    result = out.geometry.apply(lambda geom: transform(project, geom))

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\shapely\ops.py", line 252, in transform
    return type(geom)([transform(func, part) for part in geom.geoms])

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\shapely\ops.py", line 252, in <listcomp>
    return type(geom)([transform(func, part) for part in geom.geoms])

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\shapely\ops.py", line 234, in transform
    zip(*func(*izip(*geom.exterior.coords))))

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\salem\gis.py", line 676, in transform
    raise ValueError('crs not understood')

ValueError: crs not understood
```

I'll try and provide example with dataset - but it's the same as with the mwe from  nickbsb

**Comment by fmaussion** [comment]
Can you share the output of following:

```python
import xarray as xr
import salem
import geopandas
import pyproj

print(xr.__version__)
print(salem.__version__)
print(geopandas.__version__)
print(pyproj.__version__)
```

This is working on our relatively recent [binder envs](https://mybinder.org/v2/gh/OGGM/binder/master) with versions: 

```
0.12.3
0.2.4-6-g69666ac
0.5.1
1.9.6
```

**Comment by byersiiasa** [comment]
0.12.3
0.2.4-6-g69666ac
0.4.1 <<< lets see when i update.
1.9.6

**Comment by byersiiasa** [comment]
Same issue. Even tried with a clean environment.

**Comment by fmaussion** [comment]
OK, so I can only assume some upstream issue with windows / conda, most likely because of changes in pyproj.

I've added a specific test for this case in https://github.com/fmaussion/salem/pull/156 and it passes on travis, both with pyproj versions before and after 2.0 (pyproj changes have been quite tough on library maintainers lately). 

That being said, there is a pattern in salem that makes debugging your case quite difficult: we silently catch pyproj exceptions, and shouldn't do that. I'll try to think about a better pattern.

**Comment by fmaussion** [comment]
I've made an attempt to display a more informative error message in https://github.com/fmaussion/salem/pull/157 

Can you try on latest master again?

**Comment by byersiiasa** [comment]
thanks @fmaussion 
another error,  it didn't quite get to to the error message you put in...
```
Traceback (most recent call last):

  File "<ipython-input-10-7af9874e1684>", line 114, in <module>
    cropped.sel(scen='2p0-hist').salem.quick_map();

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\sio.py", line 706, in quick_map
    return self._quick_map(self._obj, ax=ax, interp=interp, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\sio.py", line 549, in _quick_map
    smap = self.get_map(**kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\sio.py", line 538, in get_map
    return Map(self.grid, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\graphics.py", line 426, in __init__
    self.set_shapefile(countries=countries)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\graphics.py", line 681, in set_shapefile
    return self.set_shapefile(shapefiles['world_borders'], **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\graphics.py", line 696, in set_shapefile
    shape = sio.read_shapefile_to_grid(shape, grid=self.grid)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\sio.py", line 117, in read_shapefile_to_grid
    **grid.to_dict())

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\joblib\memory.py", line 568, in __call__
    return self._cached_call(args, kwargs)[0]

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\joblib\memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\joblib\memory.py", line 734, in call
    output = self.func(*args, **kwargs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\sio.py", line 87, in _memory_shapefile_to_grid
    e = grid.extent_in_crs(crs=shape.crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\gis.py", line 553, in extent_in_crs
    poly = self.extent_as_polygon(crs=crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\gis.py", line 581, in extent_as_polygon
    _i, _j = self.corner_grid.ij_to_crs(_i, _j, crs=crs)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\gis.py", line 656, in ij_to_crs
    _crs = check_crs(crs, raise_on_error=True)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\salenv\lib\site-packages\salem\gis.py", line 88, in check_crs
    msg = msg.format(err1)

KeyError: "'init'"
```

**Comment by hehongjie** [comment]
@byersiiasa Hi, I met the same error as you did. Did you solve the problem? It seems that crs in my code is a dictionary type(like{‘init’: 'epsg4369'}) and gis.py cannot handle such crs.

**Comment by AnsArn** [comment]
On a fresh Ubuntu (19.10) installation with Python 3.7.5 I suddenly (it worked before) had the same Error ('Series' object has no attribute 'to_numpy'). I check my versions:

xarray version:  0.12.1
salem version:  0.2.4-13-gacb61b5
geopandas version:  0.7.0
pyproj version:  2.5.0

When I update xarray to version 0.15.0, it works again:
xarray version:  0.15.0                             
salem version:  0.2.4-13-gacb61b5                                                                        
geopandas version:  0.7.0         
pyproj version:  2.5.0

The problem occured when I tried to use the "read_shapefile_to_grid" function:
salem.read_shapefile_to_grid(shape_file,grid=salem.grid_from_dataset(era5_land_static))
Before I updated to the Salem master I hat the " ValueError: crs not understood'" Error.

**Comment by fmaussion** [comment]
>  " ValueError: crs not understood'" Error.

This is due to a geopandas update (quite strongly not backwards compatible). It should be solved on latest master. (https://github.com/fmaussion/salem/pull/164)

> ('Series' object has no attribute 'to_numpy')

This sounds like a pandas issue? What pandas version? Can you send a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by AnsArn** [comment]
Yes you are right, xarray was not the problem pandas was.
```
import pandas as pd
import xarray as xr
import salem
import geopandas
import pyproj
print("pandas version: ", pd.__version__)
print("xarray version: ", xr.__version__)
print("salem version: ", salem.__version__)
print("geopandas version: ", geopandas.__version__)
print("pyproj version: ", pyproj.__version__)
era5_land_static = salem.open_xr_dataset('ERA5_land_Z_geopotential.nc')
shape_grid = salem.read_shapefile_to_grid('Halji_RGI6.shp',grid=salem.grid_from_dataset(era5_land_static))
```

Output:
```
pandas version:  1.0.1
xarray version:  0.15.0
salem version:  0.2.4-13-gacb61b5
geopandas version:  0.7.0
pyproj version:  2.5.0

```
The problem is at the moment I can not reproduce the error, that happened one our again. :-) What I did was update xarray (at xarray updated pandas automatically).
Even when I downgrade not to pandas 0.25 or xarray 0.12.1 it work with some warning.

**Comment by fmaussion** [comment]
it's possible that something is broken with pandas > 1.0 that we are missing in our test suite. Please let me know when this happens again

**Comment by igorol** [comment]
I had the same error message using geopandas version 0.7.0, downgrading to 0.5.1 fixed it

**Comment by fmaussion** [comment]
>  using geopandas version 0.7.0

Since https://github.com/fmaussion/salem/pull/164 I hope to have solved issues with geopandas compatibility (it landed on master but not yet on PyPI). If issues remain they are not tested for, so it would be good to know ;-)
